name: build and test wasmlets

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch: {}

# only run one copy per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: "3.1.74"
      - name: Build WASM
        run: make

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install typescript dependencies
        run: yarn
      - name: Run tests
        run: yarn test

      - name: Package
        run: yarn pack

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasmlets*.tgz
